services:
  platonapp:
    container_name: appcontainer
    build:
      context: .
      target: builder
    env_file: ./.env
    restart: unless-stopped
    environment:
      - MYSQL_HOST=platondb
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      platondb:
        condition: service_healthy
    volumes:
      - ./app:/usr/src/app/app
      - prisma_client:/usr/src/app/prisma/client
    networks:
      - prisma-network

  platondb:
    image: mysql:8.0.40
    container_name: mysqlcontainer
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_ROOT_PASSWORD=$DB_PASS
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

volumes:
  db_data:
  prisma_client:

networks:
  prisma-network:
